services:
  master:
    image: mohammednumaan/shuffle:latest
    volumes:
      - /data/nfs_storage:/mnt/nfs
      - /home/numaan/.kube/config:/root/.kube/config:ro
      - /home/numaan/.minikube:/home/numaan/.minikube:ro
    command:
      - --mode=master
      - --input-dir=/mnt/nfs/input
      - --nfs-path=/mnt/nfs
      - --num-mappers=8
      - --split-size-mb=1
      - --num-reducers=4
      - --image=mohammednumaan/shuffle:latest
      - --kubeconfig=/root/.kube/config
