apiVersion: v1
kind: Pod
metadata:
  name: pod 
spec:
  containers:
    - name: alpine
      image: alpine
      volumeMounts:
        - name: nfs-vol
          mountPath: /mnt/nfs
      command: ["bin/sh", "-c", "while true; do sleep 30; done;"]

  volumes:
    - name: nfs-vol
      persistentVolumeClaim:
        claimName: nfs-pvc
