apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: shuffle
spec:
  replicas: 4
  selector:
    matchLabels:
      app: shuffle
      role: worker
  template:
    metadata:
      labels:
        app: shuffle
        role: worker
    spec:
      containers:
        - name: worker
          image: shuffle:dev
          imagePullPolicy: Never
          args:
            - -mode=worker
            - -master-addr=master.shuffle.svc:9000
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: WORKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 5001
          volumeMounts:
            - name: input
              mountPath: /data/input
            - name: output
              mountPath: /data/output
      volumes:
        - name: input
          hostPath:
            path: /tmp/shuffle-input
            type: DirectoryOrCreate
        - name: output
          hostPath:
            path: /tmp/shuffle-output
            type: DirectoryOrCreate
